# basic options
title: Data Angel on Life
author: Ã–rn Hjartarson
email: orn.hjartarson@gmail.com
Description: A great place

# Build settings
markdown: kramdown
theme: minima

github_username:  Hjartarson